# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: documentation/conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
#formats:
#  - pdf  # stopped working (e.g. https://readthedocs.org/projects/flexmeasures/builds/26604114/, also not required)

# From https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv
build:
   os: ubuntu-lts-latest
   tools:
      python: "3.12"
   jobs:
      pre_create_environment:
         - asdf plugin add uv
         - asdf install uv 0.10.3
         - asdf global uv 0.10.3
      create_environment:
         - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
      install:
         - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs

