from flexmeasures.api.sunset import (
    flexmeasures_api_v1,
    flexmeasures_api_v1_1,
    flexmeasures_api_v1_2,
    flexmeasures_api_v1_3,
    flexmeasures_api_v2_0,
)


@flexmeasures_api_v1.route("/getMeterData", methods=["GET", "POST"])
@flexmeasures_api_v1.route("/postMeterData", methods=["POST"])
@flexmeasures_api_v1.route("/getService", methods=["GET"])
@flexmeasures_api_v1_1.route("/getConnection", methods=["GET"])
@flexmeasures_api_v1_1.route("/postPriceData", methods=["POST"])
@flexmeasures_api_v1_1.route("/postWeatherData", methods=["POST"])
@flexmeasures_api_v1_1.route("/getPrognosis", methods=["GET"])
@flexmeasures_api_v1_1.route("/postPrognosis", methods=["POST"])
@flexmeasures_api_v1_1.route("/getMeterData", methods=["GET"])
@flexmeasures_api_v1_1.route("/postMeterData", methods=["POST"])
@flexmeasures_api_v1_1.route("/getService", methods=["GET"])
@flexmeasures_api_v1_2.route("/getDeviceMessage", methods=["GET"])
@flexmeasures_api_v1_2.route("/postUdiEvent", methods=["POST"])
@flexmeasures_api_v1_2.route("/getConnection", methods=["GET"])
@flexmeasures_api_v1_2.route("/postPriceData", methods=["POST"])
@flexmeasures_api_v1_2.route("/postWeatherData", methods=["POST"])
@flexmeasures_api_v1_2.route("/getPrognosis", methods=["GET"])
@flexmeasures_api_v1_2.route("/getMeterData", methods=["GET"])
@flexmeasures_api_v1_2.route("/postMeterData", methods=["POST"])
@flexmeasures_api_v1_2.route("/postPrognosis", methods=["POST"])
@flexmeasures_api_v1_2.route("/getService", methods=["GET"])
@flexmeasures_api_v1_3.route("/getDeviceMessage", methods=["GET"])
@flexmeasures_api_v1_3.route("/postUdiEvent", methods=["POST"])
@flexmeasures_api_v1_3.route("/getConnection", methods=["GET"])
@flexmeasures_api_v1_3.route("/postPriceData", methods=["POST"])
@flexmeasures_api_v1_3.route("/postWeatherData", methods=["POST"])
@flexmeasures_api_v1_3.route("/getPrognosis", methods=["GET"])
@flexmeasures_api_v1_3.route("/getMeterData", methods=["GET"])
@flexmeasures_api_v1_3.route("/postMeterData", methods=["POST"])
@flexmeasures_api_v1_3.route("/postPrognosis", methods=["POST"])
@flexmeasures_api_v1_3.route("/getService", methods=["GET"])
@flexmeasures_api_v2_0.route("/assets", methods=["GET"])
@flexmeasures_api_v2_0.route("/assets", methods=["POST"])
@flexmeasures_api_v2_0.route("/asset/<id>", methods=["GET"])
@flexmeasures_api_v2_0.route("/asset/<id>", methods=["PATCH"])
@flexmeasures_api_v2_0.route("/asset/<id>", methods=["DELETE"])
@flexmeasures_api_v2_0.route("/users", methods=["GET"])
@flexmeasures_api_v2_0.route("/user/<id>", methods=["GET"])
@flexmeasures_api_v2_0.route("/user/<id>", methods=["PATCH"])
@flexmeasures_api_v2_0.route("/user/<id>/password-reset", methods=["PATCH"])
@flexmeasures_api_v2_0.route("/getConnection", methods=["GET"])
@flexmeasures_api_v2_0.route("/postPriceData", methods=["POST"])
@flexmeasures_api_v2_0.route("/postWeatherData", methods=["POST"])
@flexmeasures_api_v2_0.route("/getPrognosis", methods=["GET"])
@flexmeasures_api_v2_0.route("/getMeterData", methods=["GET"])
@flexmeasures_api_v2_0.route("/postMeterData", methods=["POST"])
@flexmeasures_api_v2_0.route("/postPrognosis", methods=["POST"])
@flexmeasures_api_v2_0.route("/getService", methods=["GET"])
@flexmeasures_api_v2_0.route("/getDeviceMessage", methods=["GET"])
@flexmeasures_api_v2_0.route("/postUdiEvent", methods=["POST"])
def implementation_gone():
    pass
