"""empty message

Revision ID: 24de35c0a4cb
Revises: 6cf5b241b85f
Create Date: 2021-12-01 20:01:42.828139

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "24de35c0a4cb"
down_revision = "6cf5b241b85f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("power_asset_id_asset_fkey", "power", type_="foreignkey")
    op.create_foreign_key(
        op.f("power_asset_id_sensor_fkey"),
        "power",
        "sensor",
        ["asset_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("power_asset_id_sensor_fkey"), "power", type_="foreignkey")
    op.create_foreign_key(
        "power_asset_id_asset_fkey",
        "power",
        "asset",
        ["asset_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
