"""Added primary and secondary color field to account model

Revision ID: 4b5aa7856932
Revises: 126d65cbe6b4
Create Date: 2024-08-08 13:38:17.197805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4b5aa7856932"
down_revision = "126d65cbe6b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("asset")
    op.drop_table("asset_type")
    op.drop_table("weather_sensor")
    op.drop_table("market")
    op.drop_table("weather_sensor_type")
    op.drop_table("market_type")
    op.drop_table("power")
    op.drop_table("weather")
    op.drop_table("price")
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("primary_color", sa.String(length=7), nullable=True)
        )
        batch_op.add_column(
            sa.Column("secondary_color", sa.String(length=7), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_column("secondary_color")
        batch_op.drop_column("primary_color")

    op.create_table(
        "price",
        sa.Column(
            "datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("sensor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "horizon", postgresql.INTERVAL(), autoincrement=False, nullable=False
        ),
        sa.Column("data_source_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_source.id"],
            name="price_data_source_data_sources_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"], ["sensor.id"], name="price_sensor_id_sensor_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "datetime", "sensor_id", "horizon", "data_source_id", name="price_pkey"
        ),
    )
    op.create_table(
        "weather",
        sa.Column("sensor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "horizon", postgresql.INTERVAL(), autoincrement=False, nullable=False
        ),
        sa.Column("data_source_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_source.id"],
            name="weather_data_source_data_sources_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"], ["sensor.id"], name="weather_sensor_id_sensor_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "datetime", "sensor_id", "horizon", "data_source_id", name="weather_pkey"
        ),
    )
    op.create_table(
        "power",
        sa.Column(
            "datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("sensor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "horizon", postgresql.INTERVAL(), autoincrement=False, nullable=False
        ),
        sa.Column("data_source_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_source.id"],
            name="power_data_source_data_sources_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensor.id"],
            name="power_sensor_id_sensor_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "datetime", "sensor_id", "horizon", "data_source_id", name="power_pkey"
        ),
    )
    op.create_table(
        "market_type",
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column(
            "daily_seasonality", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "weekly_seasonality", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "yearly_seasonality", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "display_name",
            sa.VARCHAR(length=80),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("name", name="market_type_pkey"),
        sa.UniqueConstraint("display_name", name="market_type_display_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "weather_sensor_type",
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column(
            "display_name",
            sa.VARCHAR(length=80),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("name", name="weather_sensor_type_pkey"),
        sa.UniqueConstraint(
            "display_name", name="weather_sensor_type_display_name_key"
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "market",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('market_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column(
            "market_type_name",
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.VARCHAR(length=80),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "unit",
            sa.VARCHAR(length=80),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "event_resolution",
            postgresql.INTERVAL(),
            server_default=sa.text("'00:00:00'::interval"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "knowledge_horizon_fnc",
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "knowledge_horizon_par",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "timezone", sa.VARCHAR(length=80), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(["id"], ["sensor.id"], name="market_id_sensor_fkey"),
        sa.ForeignKeyConstraint(
            ["market_type_name"],
            ["market_type.name"],
            name="market_market_type_name_market_type_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="market_pkey"),
        sa.UniqueConstraint("display_name", name="market_display_name_key"),
        sa.UniqueConstraint("name", name="market_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "weather_sensor",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column(
            "weather_sensor_type_name",
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "unit",
            sa.VARCHAR(length=80),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.VARCHAR(length=80),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "event_resolution",
            postgresql.INTERVAL(),
            server_default=sa.text("'00:00:00'::interval"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "knowledge_horizon_fnc",
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "knowledge_horizon_par",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "timezone", sa.VARCHAR(length=80), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["sensor.id"], name="weather_sensor_id_sensor_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["weather_sensor_type_name"],
            ["weather_sensor_type.name"],
            name="weather_sensor_weather_sensor_type_name_weather_sensor__1390",
        ),
        sa.PrimaryKeyConstraint("id", name="weather_sensor_pkey"),
        sa.UniqueConstraint("name", name="weather_sensor_name_key"),
        sa.UniqueConstraint(
            "weather_sensor_type_name",
            "latitude",
            "longitude",
            name="weather_sensor_type_name_latitude_longitude_key",
        ),
    )
    op.create_table(
        "asset_type",
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column("is_consumer", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_producer", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("can_curtail", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("can_shift", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "daily_seasonality", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "weekly_seasonality", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "yearly_seasonality", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "display_name",
            sa.VARCHAR(length=80),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "hover_label", sa.VARCHAR(length=80), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("name", name="asset_type_pkey"),
        sa.UniqueConstraint("display_name", name="asset_type_display_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "asset",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "asset_type_name",
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=True),
        sa.Column(
            "display_name", sa.VARCHAR(length=80), autoincrement=False, nullable=True
        ),
        sa.Column(
            "capacity_in_mw",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "min_soc_in_mwh",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "max_soc_in_mwh",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "soc_in_mwh",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "soc_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("soc_udi_event_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "unit",
            sa.VARCHAR(length=80),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("market_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "event_resolution",
            postgresql.INTERVAL(),
            server_default=sa.text("'00:00:00'::interval"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "knowledge_horizon_fnc",
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "knowledge_horizon_par",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "timezone", sa.VARCHAR(length=80), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["asset_type_name"],
            ["asset_type.name"],
            name="asset_asset_type_name_asset_type_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["sensor.id"], name="asset_id_sensor_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["market_id"], ["market.id"], name="asset_market_id_market_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["fm_user.id"],
            name="asset_owner_id_bvp_users_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="asset_pkey"),
        sa.UniqueConstraint("display_name", name="asset_display_name_key"),
        sa.UniqueConstraint("name", name="asset_name_key"),
    )
    # ### end Alembic commands ###
